baseurl = "/"
languageCode = "en-us"
title = "Sam en Bieke"

[params]
  description = "Welkom op onze website, hier kan je meer informatie vinden over ons trouwfeest"

[[menu.main]]
    name = "Trouwdag"
    url  = "/trouwdag"
    weight = 1

