baseurl = "/"
languageCode = "en-us"
title = "Sam en Bieke"

[params]
  description = "negenentwintig mei tweeduizendnegentien"

[[menu.main]]
    name = "Ons verhaal"
    url  = "/onsverhaal"
    weight = 1

[[menu.main]]
    name = "Trouwdag"
    url  = "/trouwdag"
    weight = 2

[[menu.main]]
    name = "Kan jij er bij zijn?"
    url  = "/bevestigen"
    weight = 3


