backend:
  name: git-gateway
  repo: preben13/sam-en-bieke
  branch: master # Branch to update (optional; defaults to master)

media_folder: "src/img/gallery"

collections:
  - name: food
    label: "Food item"
    folder: "site/content/food"
    create: true
    fields:
      - { label: "Name of Item", name: "title", widget: "string"}
      - { label: "Supported Meals", name: "categories", widget: "list", default: ["breakfast", "lunch", "dinner"]}
      - { label: "Ingredients", name: "description", widget: "text" }
      - { label: "Type of food", name: "type", widget: "string", default: "raw bar"}
      - { label: "Price", name: "price", widget: "string"}
